
CREATE USER issuer_mgmt_user WITH PASSWORD 'secret';
CREATE USER oid4vci_user WITH PASSWORD 'secret';
CREATE DATABASE issuer_db;
GRANT ALL PRIVILEGES ON DATABASE issuer_db TO issuer_mgmt_user;
GRANT USAGE, CREATE ON SCHEMA public TO issuer_mgmt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO issuer_mgmt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO issuer_mgmt_user;

GRANT ALL PRIVILEGES ON DATABASE issuer_db TO oid4vci_user;
GRANT USAGE, CREATE ON SCHEMA public TO oid4vci_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO oid4vci_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO oid4vci_user;
