spring:
  datasource:
    url: "jdbc:postgresql://postgres-registry:5432/base-registry-db"
    username: "base_registry"
    password: "secret"

security:
  oauth2:
    jwt:
      issuer-uris:
        dev-issuer: https://swiyu-oauth-mock-server-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
        ref-issuer: https://swiyu-oauth-server-r.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/realms/bj-swiyu-ecosystem-portal-scs

did-authoring:
  #didTdwRouteTemplate: "http://localhost:8190/api/v1/did/{0}"
  #didWebTemplate: "did:web:localhost%3A8190:api:v1:did:{0}"
  didTdwRouteTemplate: "https://base-registry.home.rwpz.net/api/v1/did/{0}"
  didWebTemplate: "did:web:base-registry.home.rwpz.net:api:v1:did:{0}"